version: "2.0"
services:
  devlingodb:
    image: mongo
    ports:
      - 27017:27017
    container_name: "devlingodb"
  devlingoapi:
    image: devlingoapi:2.0
    ports:
      - 8080:8080
    container_name: "devlingoapi"
    links:
      - devlingodb